name: CI Healthchecks

on:
  pull_request:
    branches: [ main ]
    paths:
      - pokevoter-service/**
      - pokevoter-frontend/**

jobs:
  build-service:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        check-latest: false

    - name: Install dependencies
      run: |
        cd pokevoter-service
        npm ci

    - name: Build project
      run: |
        cd pokevoter-service
        npm run build

  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        check-latest: false

    - name: Install dependencies
      run: |
        cd pokevoter-frontend
        npm ci

    - name: Build project
      run: |
        cd pokevoter-frontend
        npm run build
